TITLE = "Student Registration"

LABEL_STUDENT_ID = "ID"
LABEL_STUDENT_NAME = "Name"
LABEL_STUDENT_COURSE = "Course"
LABEL_STUDENT_FEES = "Fees"

BUTTON_ADD = "Add"
BUTTON_UPDATE = "Update"
BUTTON_DELETE = "DELETE"

ALL_COLUMNS = (LABEL_STUDENT_ID, LABEL_STUDENT_NAME,LABEL_STUDENT_COURSE, LABEL_STUDENT_FEES)